// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { CartProvider } from "./../context/CartContext";
// import Header from "./../components/Header";
// import Footer from "../components/Footer";
// import ScrollToTop from "../components/ScrollToTop/page";
// import { Toaster } from "react-hot-toast";
// import { Inter } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-inter",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Venus Fashion",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
//       >
//         <Toaster position="top-right" />
//         <CartProvider>
//           {" "}
//           <Header />
//           {children}
//           <ScrollToTop />
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// // }
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { CartProvider } from "./../context/CartContext";
// import Header from "./../components/Header";
// import Footer from "../components/Footer";
// import ScrollToTop from "../components/ScrollToTop/page";
// import { Toaster } from "react-hot-toast";

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-inter",
// });

// export const metadata: Metadata = {
//   title: "Venus Fashion",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} antialiased overflow-x-hidden`}>
//         <Toaster position="top-right" />
//         <CartProvider>
//           <Header />
//           {children}
//           <ScrollToTop />
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./../context/CartContext";
import Header from "./../components/Header";
import Footer from "../components/Footer";
import ScrollToTop from "../components/ScrollToTop/page";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: {
    default: "VenusFashion | Exquisite Indian Luxury Apparel & Contemporary Styles",
    template: "%s | VenusFashion",
  },
  description: "VenusFashion - Discover the finest collection of luxury Indian apparel, contemporary ethnic wear, suits, kurtis, western wear, and designer fusion wear. Handcrafted premium fashion.",
  keywords: [
    "VenusFashion",
    "Venus Fashion",
    "luxury Indian clothing",
    "contemporary ethnic wear",
    "designer sarees",
    "designer lehengas",
    "premium kurtas",
    "Indian bridal wear",
    "fusion fashion",
    "designer boutique",
    "Zivore Apparel"
  ],
  authors: [{ name: "VenusFashion Team" }],
  metadataBase: new URL(process.env.NEXT_PUBLIC_SITE_URL || "https://venusfashion.store"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    title: "VenusFashion | Exquisite Indian Luxury Apparel & Contemporary Styles",
    description: "Discover the finest collection of luxury Indian apparel, contemporary ethnic wear, sarees, lehengas, kurtas, and designer fusion wear at VenusFashion.",
    url: "https://venusfashion.store",
    siteName: "VenusFashion",
    images: [
      {
        url: "/images/vflogo.png",
        width: 800,
        height: 600,
        alt: "VenusFashion Luxury Boutique Logo",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "VenusFashion | Exquisite Indian Luxury Apparel & Contemporary Styles",
    description: "Discover the finest collection of luxury Indian apparel, contemporary ethnic wear, sarees, lehengas, kurtas, and designer fusion wear at VenusFashion.",
    images: ["/images/vflogo.png"],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Store",
    "name": "VenusFashion",
    "image": "https://venusfashion.store/images/vflogo.png",
    "description": "Exquisite Indian Luxury Apparel & Contemporary Styles",
    "url": "https://venusfashion.store",
    "telephone": "+91 9899990772",
    "address": {
      "@type": "PostalAddress",
      "streetAddress": "B 005, Sector 85",
      "addressLocality": "Noida",
      "addressRegion": "Uttar Pradesh",
      "postalCode": "201301",
      "addressCountry": "IN"
    },
    "sameAs": [
      "https://www.facebook.com/venusfashion",
      "https://www.instagram.com/venusfashion2020"
    ]
  };

  return (
    <html lang="en">
      <head>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${inter.variable} ${cormorant.variable} font-sans antialiased overflow-x-hidden flex flex-col min-h-screen`}
      >
        <Toaster position="top-right" />

        <CartProvider>
          <Header />

          {/* Main Content */}
          <main className="flex-grow bg-[#FCFCFC]">{children}</main>

          <ScrollToTop />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
