// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { CartProvider } from "./../context/CartContext";
// import Header from "./../components/Header";
// import Footer from "../components/Footer";
// import ScrollToTop from "../components/ScrollToTop/page";
// import { Toaster } from "react-hot-toast";
// import { Inter } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-inter",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Venus Fashion",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${inter.className} ${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
//       >
//         <Toaster position="top-right" />
//         <CartProvider>
//           {" "}
//           <Header />
//           {children}
//           <ScrollToTop />
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// // }
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { CartProvider } from "./../context/CartContext";
// import Header from "./../components/Header";
// import Footer from "../components/Footer";
// import ScrollToTop from "../components/ScrollToTop/page";
// import { Toaster } from "react-hot-toast";

// const inter = Inter({
//   subsets: ["latin"],
//   display: "swap",
//   variable: "--font-inter",
// });

// export const metadata: Metadata = {
//   title: "Venus Fashion",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={`${inter.className} antialiased overflow-x-hidden`}>
//         <Toaster position="top-right" />
//         <CartProvider>
//           <Header />
//           {children}
//           <ScrollToTop />
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./../context/CartContext";
import Header from "./../components/Header";
import Footer from "../components/Footer";
import ScrollToTop from "../components/ScrollToTop/page";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Venus Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-x-hidden flex flex-col min-h-screen`}
      >
        <Toaster position="top-right" />

        <CartProvider>
          <Header />

          {/* Main Content */}
          <main className="flex-grow">{children}</main>

          <ScrollToTop />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
